// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *uic_temperatureValue;
lv_obj_t *uic_temperatureBar;
lv_obj_t *uic_temperatureTitle;
lv_obj_t *uic_humidityValue;
lv_obj_t *uic_humidityBar;
lv_obj_t *uic_humidityTitle;
lv_obj_t *ui_scrMain = NULL;lv_obj_t *ui_humidityTitle = NULL;lv_obj_t *ui_humidityBar = NULL;lv_obj_t *ui_humidityValue = NULL;lv_obj_t *ui_temperatureTitle = NULL;lv_obj_t *ui_temperatureBar = NULL;lv_obj_t *ui_temperatureValue = NULL;
// event funtions

// build funtions

void ui_scrMain_screen_init(void)
{
ui_scrMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_humidityTitle = lv_label_create(ui_scrMain);
lv_obj_set_width( ui_humidityTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidityTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidityTitle, -80 );
lv_obj_set_y( ui_humidityTitle, -32 );
lv_obj_set_align( ui_humidityTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidityTitle,"Umidade");

ui_humidityBar = lv_bar_create(ui_scrMain);
lv_obj_set_width( ui_humidityBar, 240);
lv_obj_set_height( ui_humidityBar, 10);
lv_obj_set_align( ui_humidityBar, LV_ALIGN_CENTER );

ui_humidityValue = lv_label_create(ui_scrMain);
lv_obj_set_width( ui_humidityValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidityValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidityValue, 0 );
lv_obj_set_y( ui_humidityValue, 32 );
lv_obj_set_align( ui_humidityValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidityValue,"");

ui_temperatureTitle = lv_label_create(ui_scrMain);
lv_obj_set_width( ui_temperatureTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperatureTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temperatureTitle, -72 );
lv_obj_set_y( ui_temperatureTitle, 64 );
lv_obj_set_align( ui_temperatureTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperatureTitle,"Temperatura");

ui_temperatureBar = lv_bar_create(ui_scrMain);
lv_obj_set_width( ui_temperatureBar, 240);
lv_obj_set_height( ui_temperatureBar, 10);
lv_obj_set_x( ui_temperatureBar, 0 );
lv_obj_set_y( ui_temperatureBar, 96 );
lv_obj_set_align( ui_temperatureBar, LV_ALIGN_CENTER );

ui_temperatureValue = lv_label_create(ui_scrMain);
lv_obj_set_width( ui_temperatureValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperatureValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temperatureValue, 0 );
lv_obj_set_y( ui_temperatureValue, 128 );
lv_obj_set_align( ui_temperatureValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperatureValue,"");

uic_humidityTitle = ui_humidityTitle;
uic_humidityBar = ui_humidityBar;
uic_humidityValue = ui_humidityValue;
uic_temperatureTitle = ui_temperatureTitle;
uic_temperatureBar = ui_temperatureBar;
uic_temperatureValue = ui_temperatureValue;

}

void ui_scrMain_screen_destroy(void)
{
   if (ui_scrMain) lv_obj_del(ui_scrMain);

// NULL screen variables
ui_scrMain= NULL;
uic_humidityTitle= NULL;
ui_humidityTitle= NULL;
uic_humidityBar= NULL;
ui_humidityBar= NULL;
uic_humidityValue= NULL;
ui_humidityValue= NULL;
uic_temperatureTitle= NULL;
ui_temperatureTitle= NULL;
uic_temperatureBar= NULL;
ui_temperatureBar= NULL;
uic_temperatureValue= NULL;
ui_temperatureValue= NULL;

}
