// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t *ui_scrMain;
extern lv_obj_t *ui_humidityTitle;
extern lv_obj_t *ui_humidityBar;
extern lv_obj_t *ui_humidityValue;
extern lv_obj_t *ui_temperatureTitle;
extern lv_obj_t *ui_temperatureBar;
extern lv_obj_t *ui_temperatureValue;
// CUSTOM VARIABLES
extern lv_obj_t *uic_humidityTitle;
extern lv_obj_t *uic_humidityBar;
extern lv_obj_t *uic_humidityValue;
extern lv_obj_t *uic_temperatureTitle;
extern lv_obj_t *uic_temperatureBar;
extern lv_obj_t *uic_temperatureValue;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

